Coombi125565/Controllers/GroupController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Coombi125565.Models;
using WebMatrix.WebData;

namespace Coombi125565.Controllers
{
    public class GroupController : Controller
    {
        private MyContext db = new MyContext();
        
        //See all my groups //link create a new group
        public ActionResult Index()
        {
            List<GroupModel> result = db.Groups.SqlQuery("SELECT Groups.* FROM Groups JOIN GroupMembership ON GroupMembership.GroupId = Groups.GroupId WHERE GroupMemberShip.UserId = " + WebSecurity.CurrentUserId + ";").ToList();
            List<GroupModel> mygroups = db.Groups.Where(g => g.OwnerId == WebSecurity.CurrentUserId).ToList();
            foreach (GroupModel group in mygroups) {
                result.Add(group);
            }
            return View(result);
        }

        // GET: /Group/Details/5 , See time of a group
        //if my group, link manage group members
        public ActionResult Details(int id = 0)
        {
            GroupModel groupmodel = db.Groups.Find(id);
            if (groupmodel == null)
            {
                return HttpNotFound();
            }
            List<PostModel> posts = db.Posts.Where(post => post.GroupId == id).OrderBy(post => post.Time).ToList();
            posts.Reverse();

            List<UserProfile> members = db.Users.SqlQuery("SELECT UserProfile.* FROM UserProfile JOIN GroupMembership ON GroupMembership.UserId = UserProfile.UserId WHERE GroupMembership.GroupId = " + id + ";").ToList();
            return View(new DetailsGroup {Group = groupmodel, Posts = posts, Members = members});
        }

        //Create a new Group
        public ActionResult Create()
        {
            return View();
        }
        // POST: /Group/Create
        [HttpPost]
        public ActionResult Create(AddGroupModel addgroupmodel)
        {
            if (ModelState.IsValid)
            {
                GroupModel group = new GroupModel();
                group.Name = addgroupmodel.Name;
                group.OwnerId = WebSecurity.CurrentUserId;
                db.Groups.Add(group);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(addgroupmodel);
        }

        // GET: /Group/Delete/5
        public ActionResult Delete(int id = 0)
        {
            GroupModel groupmodel = db.Groups.Find(id);
            if (groupmodel == null)
            {
                return HttpNotFound();
            }
            return View(groupmodel);
        }
        // POST: /Group/Delete/5
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            GroupModel groupmodel = db.Groups.Find(id);
            db.Groups.Remove(groupmodel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        //Unsuscribe for a group
        public ActionResult Unsuscribe(int id = 0)
        {
            List<GroupMembershipModel> gms = db.GroupMemberships.Where(g => g.GroupId == id && g.UserId == WebSecurity.CurrentUserId).ToList();
            foreach (GroupMembershipModel gm in gms)
            {
                db.GroupMemberships.Remove(gm);
            }
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        //Manage group member
        public ActionResult Manage(int id = 0)
        {
            List<UserProfile> Users = db.Users.Where(u => u.UserId != WebSecurity.CurrentUserId).ToList();
            List<GroupMembershipModel> gms = db.GroupMemberships.Where(g => g.GroupId == id).ToList();
            List<int> Members = new List<int>();
            foreach (GroupMembershipModel gm in gms) {
                Members.Add(gm.UserId);
            }
            return View(new ManageUsersGroup {Members = Members, Users = Users, Group = db.Groups.Find(id) });
        }
        [HttpPost]
        public ActionResult Manage(List<int> Members = null, int id = 0)
        {
            if (Members == null) {
                Members = new List<int>();
            }
            //On supprime les entrées pour ce groupe
            List<GroupMembershipModel> gms = db.GroupMemberships.Where(g => g.GroupId == id).ToList();
            foreach (GroupMembershipModel gm in gms) {
                db.GroupMemberships.Remove(gm);
            }
            foreach (int u in Members) {
                db.GroupMemberships.Add(new GroupMembershipModel {GroupId = id, UserId = u });
            }
            db.SaveChanges();
            List<UserProfile> Users = db.Users.Where(u => u.UserId != WebSecurity.CurrentUserId).ToList();
            return View(new ManageUsersGroup { Members = Members, Users = Users, Group = db.Groups.Find(id) });
        }
    }
}

Coombi125565/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - Cöombi BETOU Yannick</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Styles.Render("~/Content/mycss.css")
        @Scripts.Render("~/bundles/modernizr")
        @Scripts.Render("~/Scripts/jquery-1.7.1.js")
        @Scripts.Render("~/Scripts/myjs.js")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p id="coombi-title">
                        <a href="/">C<span class="coombi-first-o">ö</span><span class="coombi-second-o">o</span>mbi</a>
                    </p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Timeline", "Index", "Index")</li>
                            <li>@Html.ActionLink("Groups", "Index", "Group")</li>
                            <li>@Html.ActionLink("Users", "Index", "User")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - Cöombi BETOU Yannick</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>